// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReferenceReferralApp.Models;

namespace ReferenceReferralApp.Migrations
{
    [DbContext(typeof(ReferenceContext))]
    [Migration("20201018180100_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ReferenceReferralApp.Models.Reference", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("ID");

                    b.ToTable("References");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            email = "Brett@email,com",
                            firstName = "Brett",
                            lastName = "Maiki"
                        },
                        new
                        {
                            ID = 2,
                            email = "Brett@email,com",
                            firstName = "Brad",
                            lastName = "Maiki"
                        },
                        new
                        {
                            ID = 3,
                            email = "Brett@email,com",
                            firstName = "Sally",
                            lastName = "Maiki"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
